---
- name: Check if Homebrew is installed.
  stat: path=/usr/local/bin/brew follow=yes get_md5=no
  register: homebrew
- name: Install Homebrew.
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not homebrew.stat.exists
- name: Install node.js and npm.
  homebrew: name=node state=present install_options=with-npm update_homebrew=no
