---
- name: Create a personal git configuration file.
  template:
    src=gitconfig.j2
    dest=~/.gitconfig

- name: Create a personal global gitignore file.
  template:
    src=gitignore_global.j2
    dest=~/.gitignore_global
