---
- name: Install js-lint.
  shell: >
    PATH=$PATH:/usr/local/bin npm install jslint -g

- name: Install js-yaml.
  shell: >
    PATH=$PATH:/usr/local/bin npm install js-yaml -g

- name: Install CSS lint.
  shell: >
    PATH=$PATH:/usr/local/bin npm install csslint -g
