---

- hosts: local
  gather_facts: smart

  vars_files:
    - vars/main.yml

  pre_tasks:
  - include: tasks/package-managers.yml

  roles:
    - git-config
    - vim
    - syntax-checkers
    - php
    - drush
    - vim-drupal
    - gui-apps
